- alias: Set nighttime
  description: 'Set input_number.nighttime depending on the current time.'
  trigger:
  - platform: time
    at: "06:00:00"
  - platform: time
    at: "22:00:00"
  condition: []
  action:
  - service: input_number.set_value
    data:
      entity_id: input_number.nighttime
      value: >
        {% if now().hour | int == 6 %}
        0
        {% else %}
        1
        {% endif %}
