- alias: Kitchen Motion Detected
  description: Tuns the lights on in the kitchen when motion is detected.
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      before_offset: +02:00:00
      condition: sun
    - after: sunset
      after_offset: -01:00:00
      condition: sun
  action:
  - variables:
      brightness:
        day: 85
        night: 10
  - service: light.turn_on
    entity_id: light.kitchen_ceiling_light
    data:
      brightness_pct: >
        {% if states('input_number.nighttime') | int == 0 %}
        {{ brightness.day }}
        {% else %}
        {{ brightness.night }}
        {% endif %}
  mode: single

- alias: Kitchen Motion Not Detected
  description: Turns the lights off in the kitchen when no motion is registered for some time.
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 0:01:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      transition: 60
    entity_id: light.kitchen_ceiling_light
    service: light.turn_off
  mode: restart
