- id: '1596821066084'
  alias: Living Room Switch Toggle lights
  description: Turns the lights on in the living room by the press of a button
  trigger:
  - device_id: b97c5611860c431e901dc2ecdde40f22
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Living Room
  condition: []
  action:
  - data: {}
    entity_id: light.living_room_ceiling_light
    service: script.toggle_living_room
  mode: single
- id: '1596821331812'
  alias: Living Room Switch Dim lights up
  description: ''
  trigger:
  - device_id: b97c5611860c431e901dc2ecdde40f22
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  condition: []
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.living_room_ceiling_light
    service: light.turn_on
  mode: single
- id: '1596821394621'
  alias: Living Room Switch Dim lights down
  description: ''
  trigger:
  - device_id: b97c5611860c431e901dc2ecdde40f22
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  condition: []
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.living_room_ceiling_light
    service: light.turn_on
  mode: single
- id: '1596824265606'
  alias: Kitchen Switch Turn light on
  description: ''
  trigger:
  - device_id: 2962ebafc9194ec487725951942576ad
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition:
  - condition: state
    entity_id: light.kitchen_ceiling_light
    state: 'off'
  action:
  - data:
      brightness_pct: 85
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  - data: {}
    entity_id: automation.kitchen_motion_not_detected
    service: automation.turn_off
  - data:
      duration: '1:00:00'
    entity_id: timer.kitchen_motion_disable
    service: timer.start
  mode: single
- id: '1596824355520'
  alias: Kitchen Switch Turn lights off
  description: ''
  trigger:
  - device_id: 2962ebafc9194ec487725951942576ad
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_short_press
  condition:
  - condition: state
    entity_id: light.kitchen_ceiling_light
    state: 'on'
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_off
  - data: {}
    entity_id: timer.kitchen_motion_disable
    service: timer.finish
  mode: single
- id: '1596824474007'
  alias: Kitchen Switch Dim lights up
  description: ''
  trigger:
  - device_id: 2962ebafc9194ec487725951942576ad
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition:
  - condition: state
    entity_id: light.kitchen_ceiling_light
    state: 'on'
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  - data: {}
    entity_id: automation.kitchen_motion_not_detected
    service: automation.turn_off
  - data:
      duration: '1:00:00'
    entity_id: timer.kitchen_motion_disable
    service: timer.start
  mode: single
- id: '1596824558334'
  alias: Kitchen Switch Dim lights down
  description: ''
  trigger:
  - device_id: 2962ebafc9194ec487725951942576ad
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_long_press
  condition:
  - condition: state
    entity_id: light.kitchen_ceiling_light
    state: 'on'
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  mode: single
- id: '1596828920288'
  alias: Bedroom Toggle All lights
  description: ''
  trigger:
  - device_id: 9dec237dd3e041cba183eeac96ef37b8
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Bedroom
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - data: {}
    entity_id: light.bedroom_ceiling_light
    service: script.toggle_bedroom_lights
  mode: single
- id: '1596901034041'
  alias: Bedroom Dim Ceiling lights up
  description: ''
  trigger:
  - device_id: 9dec237dd3e041cba183eeac96ef37b8
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  condition: []
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.bedroom_ceiling_light
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1596901058445'
  alias: Bedroom Dim Ceiling lights down
  description: ''
  trigger:
  - device_id: 9dec237dd3e041cba183eeac96ef37b8
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  condition: []
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.bedroom_ceiling_light
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1598220220014'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.robin
    for: 0:10:00
    from: Home
    platform: state
    to: Away
  condition: []
  action:
  - service: automation.trigger
    data: {}
    entity_id: automation.turn_off_all_lights
  mode: single
- id: '1600627887713'
  alias: Turn off all lights
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Turn off all lights
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  condition: []
  action:
  - service: script.turn_off_all_lights
    data: {}
  mode: single
- id: '1610728881977'
  alias: Bedroom Toggle Light Bed Left
  description: ''
  trigger:
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: left
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: left
  - device_id: 9dec237dd3e041cba183eeac96ef37b8
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: right
  condition: []
  action:
  - variables:
      ceiling_light:
        brightness: 75
        color_temp: 350
      bed_light:
        brightness: 35
        color_temp: 350
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: light.bedroom_bed_light_left
          state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.bedroom_bed_light_left
        data:
          brightness_pct: '{{ bed_light.brightness }}'
          color_temp: '{{ bed_light.color_temp }}'
    default:
    - service: light.turn_off
      entity_id: light.bedroom_bed_light_left
      data: {}
  mode: single
- id: '1610729404767'
  alias: Bedroom Toggle Light Bed Right
  description: ''
  trigger:
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: right
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: right
  - device_id: 9dec237dd3e041cba183eeac96ef37b8
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: left
  condition: []
  action:
  - variables:
      ceiling_light:
        brightness: 75
        color_temp: 350
      bed_light:
        brightness: 35
        color_temp: 350
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: light.bedroom_bed_light_right
          state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.bedroom_bed_light_right
        data:
          brightness_pct: '{{ bed_light.brightness }}'
          color_temp: '{{ bed_light.color_temp }}'
    default:
    - service: light.turn_off
      entity_id: light.bedroom_bed_light_right
      data: {}
  mode: single
- id: '1610730429167'
  alias: Bedroom Dim Lights Bed Left Up
  description: ''
  trigger:
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  condition: []
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.bedroom_bed_light_left
    service: light.turn_on
  mode: single
  max: 10
- id: '1610730547463'
  alias: Bedroom Dim Lights Bed Left Down
  description: ''
  trigger:
  - device_id: f42fb3ab59acbf4aa6aeb4f866664703
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  condition: []
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.bedroom_bed_light_left
    service: light.turn_on
  mode: single
  max: 10
- id: '1610730791668'
  alias: Bedroom Dim Lights Bed Right Down
  description: ''
  trigger:
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  condition: []
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.bedroom_bed_light_right
    service: light.turn_on
  mode: single
  max: 10
- id: '1610730863611'
  alias: Bedroom Dim Lights Bed Right Up
  description: ''
  trigger:
  - device_id: f2759b059df72bf6dd69b11c7a084d4f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  condition: []
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.bedroom_bed_light_right
    service: light.turn_on
  mode: single
  max: 10
