---

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warning
  logs:
    homeassistant.components.python_script: info

# Global variables using the variable integration from hacs
var: !include variables.yaml

# Base Settings
homeassistant:
  name: !secret base_name
  internal_url: !secret base_internal_url
  external_url: !secret base_external_url
  latitude: !secret base_latitude
  longitude: !secret base_longitude
  elevation: !secret base_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Berlin
  customize: !include customize.yaml

logbook: !include logbook.yaml
history: !include history.yaml

# Server Settings
http: !include server.yaml
frontend:
  themes: !include_dir_merge_named themes

# Basic Grouping
group: !include groups.yaml
light groups: !include light_groups.yaml

# Here be dragons. Also this is where the magic happens
input_number: !include input_number.yaml
timer: !include timers.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/

# Enable python scripts
python_script:

# Dashboards
lovelace: !include lovelace.yaml

# Integrations
icloud: !include icloud.yaml
ios: !include ios.yaml
spotify: !include spotify.yaml
withings: !include withings.yaml

tts:
  - platform: google_translate
