---

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:

# Base Settings
homeassistant:
  name: !secret base_name
  internal_url: !secret base_internal_url
  external_url: !secret base_external_url
  latitude: !secret base_latitude
  longitude: !secret base_longitude
  elevation: !secret base_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Berlin
  customize: !include system/customize.yaml

logbook: !include system/logbook.yaml
history: !include system/history.yaml

# Server Settings
logger: !include system/logger.yaml
http: !include system/server.yaml
frontend:
  themes: !include_dir_merge_named system/themes

# Groups
group: !include groups/groups.yaml
light groups: !include groups/light_groups.yaml

# Entities
input_boolean: !include entities/inputs/input_boolean.yaml
input_number: !include entities/inputs/input_number.yaml
binary_sensor: !include entities/binary_sensor.yaml
timer: !include entities/timers.yaml

# Actions
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list actions/automations/
scene: !include actions/scenes.yaml
script: !include scripts.yaml

# Dashboards
lovelace: !include dashboards/lovelace.yaml

# Integrations
ios: !include integrations/ios.yaml
spotify: !include integrations/spotify.yaml
tts: !include integrations/tts.yaml
var: !include integrations/variables.yaml
withings: !include integrations/withings.yaml
