---

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:

# Base Settings
homeassistant:
  name: !secret base_name
  internal_url: !secret base_internal_url
  external_url: !secret base_external_url
  latitude: !secret base_latitude
  longitude: !secret base_longitude
  elevation: !secret base_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Berlin
  customize: !include system/customize.yaml

logbook: !include system/logbook.yaml
history: !include system/history.yaml

# Server Settings
logger: !include system/logger.yaml
http: !include system/server.yaml
frontend:
  themes: !include_dir_merge_named system/themes

# Global variables using the variable integration from hacs
var: !include variables.yaml

# Basic Grouping
group: !include groups.yaml
light groups: !include light_groups.yaml

# Here be dragons. Also this is where the magic happens
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
timer: !include timers.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/

# Dashboards
lovelace: !include lovelace.yaml

# Integrations
ios: !include integrations/ios.yaml
spotify: !include integrations/spotify.yaml
tts: !include integrations/tts.yaml
withings: !include integrations/withings.yaml
