- alias: Reenable Kitchen Motion Senour
  description: 'Reenable the motion Sensor in the kitchen after the corresponding timer run out.'
  trigger:
  - platform: event
    event_data:
      entity_id: timer.kitchen_motion_disable
    event_type: timer.finished
  condition: []
  action:
  - service: automation.turn_on
    entity_id: automation.kitchen_motion_not_detected
    data: {}
  - condition: device
    device_id: f795a2894ae84f93b27efb9486fb7721
    entity_id: binary_sensor.kitchen_motion
    domain: binary_sensor
    type: is_no_motion
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - service: light.turn_off
    entity_id: light.kitchen_ceiling_light
    data: {}
